version: '3.3'

services:
    wordpress:
        build: .
        restart: always
        ports:
            - 8000:80
        environment:
            WORDPRESS_DB_HOST:
            WORDPRESS_DB_USER:
            WORDPRESS_DB_PASSWORD:
            WORDPRESS_DB_NAME:
            
    db:
        image: mysql:5.7
        restart: always
        environment:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        volumes:
            - db:/var/lib/mysql
    adminer:
        depends_on:
            - db
        images: adminer
        restart: always
        ports:
            - 8888:8080

networks:
    back:
    
volumes:
    db: